### ISSUE TITLE
Simple Function parse fails (browser)

### ISSUE THREAD

**Issue by thecodedrift** [sebmarkbage/link.js#4]
``` js
function() {
  return 'a';
}
```

``` js
LinkJS.parse(theAboveFile);
```

The tokenizer barfs on the expect("(") call, as it's already lex()-ed to ) in the string. Workaround is to rewrite the function with a function name, which gets past the lex problems.

Sample of us using our workaround: https://github.com/Jakobo/inject/blob/test_restructure/src/requirecontext.js#L327

**Comment by sebmarkbage** [comment]
Yea, LinkJS expects a JavaScript source file. Your example is not a valid JavaScript statement. I'm hesitant to support it since there may be other corner cases that could be contradictory. I guess I could supply an API to specifically parse an expression but a much simpler solution is to wrap it in parenthesis. That should work whether it's a function or literal.

``` js
(function() {
  return 'a';
})
```

``` js
('a')
```

If you want to parse an expression you can simply do:

``` js
linkjs.parse('(' + expression + ')')
```

**Comment by thecodedrift** [comment]
That's a simple enough explanation for me. Thanks for the update.
